// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-02-09 22:29:36.873447675 -0300 -03 m=+0.056800132

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a sample server Petstore server.",
        "title": "Swagger Example API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "/api/v1",
    "paths": {
        "/login": {
            "post": {
                "description": "verifica na base se existe as credenciais passadas, e retorna um token caso exista.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "realizar login",
                "parameters": [
                    {
                        "description": "Login",
                        "name": "Passageiro",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/dtos.CredenciaisDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ResponseToken"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/passageiro": {
            "get": {
                "description": "Retorna todos os passageiros cadastrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passageiro"
                ],
                "summary": "Show a passageiro",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Passageiro"
                            }
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Metodo para atualizar um voo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passageiro"
                ],
                "summary": "Show a voo",
                "parameters": [
                    {
                        "description": "Passageiro",
                        "name": "Passageiro",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Passageiro"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Passageiro atualizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Metodo que cadastrar passageiro",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passageiro"
                ],
                "summary": "Show a passageiro",
                "parameters": [
                    {
                        "description": "Passageiro",
                        "name": "Passageiro",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/dtos.PassageiroDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Passageiro cadastrado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/passageiro/{idPassageiro}": {
            "get": {
                "description": "Retorna o passageiros cadastrado com base no idPassageiro passado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passageiro"
                ],
                "summary": "Show a passageiro",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "IdPassageiro",
                        "name": "idVoo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Passageiro"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/passagem": {
            "get": {
                "description": "Metodo para buscar passagem passando o id da passagem como referencia",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passagem"
                ],
                "summary": "Show a passagens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Passagem"
                            }
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Metodo atualiza uma passagem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passagem"
                ],
                "summary": "Show a passagens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Passagem"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Metodo para registrar uma pasagem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passagem"
                ],
                "summary": "Show a passagens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Passagem"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Metodo para excluir uma pasagem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passagem"
                ],
                "summary": "Show a passagens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Passagem"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/voo": {
            "get": {
                "description": "Retorna todos os voos cadastrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voo"
                ],
                "summary": "Show a voo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Voo"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Metodo para atualizar um voo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voo"
                ],
                "summary": "Show a voo",
                "responses": {
                    "200": {},
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Metodo que cadastrar voos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voo"
                ],
                "summary": "Show a voo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "IdVoo",
                        "name": "idVoo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Voo"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Metodo que cadastrar voos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voo"
                ],
                "summary": "Show a voo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "IdVoo",
                        "name": "idVoo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IdVoo",
                        "name": "destino",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IdVoo",
                        "name": "horaSaida",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "IdVoo",
                        "name": "capacidade",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Voo"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/voo/{idVoo}": {
            "get": {
                "description": "Retorna o voo cadastrado com base no idVoo passado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voo"
                ],
                "summary": "Show a voo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "IdVoo",
                        "name": "idVoo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Voo"
                        }
                    },
                    "400": {
                        "description": "Requisição invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Nenhum registro encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CredenciaisDto": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "dtos.PassageiroDto": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "models.Passageiro": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "idPassageiro": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "models.Passagem": {
            "type": "object",
            "properties": {
                "dataCompra": {
                    "type": "string"
                },
                "idPassageiro": {
                    "type": "integer"
                },
                "idPassagem": {
                    "type": "integer"
                },
                "idVoo": {
                    "type": "integer"
                },
                "numeroAcento": {
                    "type": "integer"
                }
            }
        },
        "models.ResponseToken": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.Voo": {
            "type": "object",
            "properties": {
                "capacidade": {
                    "type": "integer"
                },
                "destino": {
                    "type": "string"
                },
                "horaSaida": {
                    "type": "string"
                },
                "idVoo": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
